logging:
  level:
    org:
      apache:
        http: DEBUG
      hibernate:
        SQL: DEBUG
        type: TRACE
      springframework:
        web:
          client.RestTemplate: DEBUG
server:
  port: 9090
spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
    show-sql: true
  sql:
    init:
      mode: always
---
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    password: root
    url: jdbc:postgresql://localhost:5432/statsdb
    username: root
  jpa:
    show-sql: true
---
spring:
  config:
    activate:
      on-profile: ci,test,default
  datasource:
    driverClassName: org.h2.Driver
    password: test
    url: jdbc:h2:mem:statsdb
    username: test